 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/menu_items", type: :request do
  # Api::MenuItem. As you add validations to Api::MenuItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Api::MenuItem.create! valid_attributes
      get api_menu_items_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      menu_item = Api::MenuItem.create! valid_attributes
      get api_menu_item_url(api_menu_item)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_api_menu_item_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      menu_item = Api::MenuItem.create! valid_attributes
      get edit_api_menu_item_url(api_menu_item)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Api::MenuItem" do
        expect {
          post api_menu_items_url, params: { api_menu_item: valid_attributes }
        }.to change(Api::MenuItem, :count).by(1)
      end

      it "redirects to the created api_menu_item" do
        post api_menu_items_url, params: { api_menu_item: valid_attributes }
        expect(response).to redirect_to(api_menu_item_url(@api_menu_item))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Api::MenuItem" do
        expect {
          post api_menu_items_url, params: { api_menu_item: invalid_attributes }
        }.to change(Api::MenuItem, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post api_menu_items_url, params: { api_menu_item: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested api_menu_item" do
        menu_item = Api::MenuItem.create! valid_attributes
        patch api_menu_item_url(api_menu_item), params: { api_menu_item: new_attributes }
        menu_item.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the api_menu_item" do
        menu_item = Api::MenuItem.create! valid_attributes
        patch api_menu_item_url(api_menu_item), params: { api_menu_item: new_attributes }
        menu_item.reload
        expect(response).to redirect_to(api_menu_item_url(menu_item))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        menu_item = Api::MenuItem.create! valid_attributes
        patch api_menu_item_url(api_menu_item), params: { api_menu_item: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested api_menu_item" do
      menu_item = Api::MenuItem.create! valid_attributes
      expect {
        delete api_menu_item_url(api_menu_item)
      }.to change(Api::MenuItem, :count).by(-1)
    end

    it "redirects to the api_menu_items list" do
      menu_item = Api::MenuItem.create! valid_attributes
      delete api_menu_item_url(api_menu_item)
      expect(response).to redirect_to(api_menu_items_url)
    end
  end
end
