 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/restaurants", type: :request do
  # Api::Restaurant. As you add validations to Api::Restaurant, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Api::Restaurant.create! valid_attributes
      get api_restaurants_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      restaurant = Api::Restaurant.create! valid_attributes
      get api_restaurant_url(api_restaurant)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_api_restaurant_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      restaurant = Api::Restaurant.create! valid_attributes
      get edit_api_restaurant_url(api_restaurant)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Api::Restaurant" do
        expect {
          post api_restaurants_url, params: { api_restaurant: valid_attributes }
        }.to change(Api::Restaurant, :count).by(1)
      end

      it "redirects to the created api_restaurant" do
        post api_restaurants_url, params: { api_restaurant: valid_attributes }
        expect(response).to redirect_to(api_restaurant_url(@api_restaurant))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Api::Restaurant" do
        expect {
          post api_restaurants_url, params: { api_restaurant: invalid_attributes }
        }.to change(Api::Restaurant, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post api_restaurants_url, params: { api_restaurant: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested api_restaurant" do
        restaurant = Api::Restaurant.create! valid_attributes
        patch api_restaurant_url(api_restaurant), params: { api_restaurant: new_attributes }
        restaurant.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the api_restaurant" do
        restaurant = Api::Restaurant.create! valid_attributes
        patch api_restaurant_url(api_restaurant), params: { api_restaurant: new_attributes }
        restaurant.reload
        expect(response).to redirect_to(api_restaurant_url(restaurant))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        restaurant = Api::Restaurant.create! valid_attributes
        patch api_restaurant_url(api_restaurant), params: { api_restaurant: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested api_restaurant" do
      restaurant = Api::Restaurant.create! valid_attributes
      expect {
        delete api_restaurant_url(api_restaurant)
      }.to change(Api::Restaurant, :count).by(-1)
    end

    it "redirects to the api_restaurants list" do
      restaurant = Api::Restaurant.create! valid_attributes
      delete api_restaurant_url(api_restaurant)
      expect(response).to redirect_to(api_restaurants_url)
    end
  end
end
